### ISSUE TITLE
Invalid license in manifest.

### ISSUE THREAD

**Issue by sergiotarxz** [bludit-themes/massively#4]
There are many Creative Commons licenses which one applies must be said.

If no license can be found in many legislations that is equal to privative software and distribution and modification can not be done because all rights are reserved to the author or copyright holder.

The complete license is said in README but still there are no copy of the License attached to the repository and copyright holder is not clear in files.

For example is not clear if Bludit itself holds the copyright or Diego.

**Comment by dignajar** [comment]
Please do not create these kinds of issues, just create the PR with the LICENSE.
In the readme, there is information about the developers and the license.
